---
app:
  webUser: www-data
  webGroup: www-data
site:
  domain:
  - dist.webird.io
  - www.dist.webird.io
  mail:
    name: Webird
    email: notification-noreply@webird.io
database:
  host: localhost
  dbname: webird
  username: root
  password: root
security:
  salt: CHANGE ME!!!
  cryptKey: CHANGE ME!!!
services:
  google:
    clientId: ""
    clientSecret: ""
  microsoft:
    clientId: ""
    clientSecret: ""
mailer:
  driver: smtp
  host: smtp.gmail.com
  port: "587"
  encryption: tls
  username: ""
  password: ""
...
